"use client";

import React, { useState } from "react";

/**
 * DVLReport — PDF Audit Report Generator (Session 12B)
 * Client-side PDF generation using @react-pdf/renderer.
 * Generates a downloadable compliance-grade audit trail.
 *
 * The B2B feature: hedge fund analysts run queries, export clean audit PDF.
 */

interface ReportEntry {
  question: string;
  raw_number: number | null;
  verified_number: number | null;
  trust_score: string;
  trust_color: string;
  correction_log: Array<{ rule: string; before: number; after: number; description?: string }>;
  display_value?: string;
}

interface DVLReportProps {
  entries: ReportEntry[];
  ticker?: string;
}

/* ── Client-side PDF generator (no SSR) ── */
async function generatePDF(entries: ReportEntry[], ticker?: string): Promise<Blob> {
  const {
    Document, Page, Text, View, StyleSheet, pdf,
  } = await import("@react-pdf/renderer");
  const React = (await import("react")).default;

  const dateStr = new Date().toISOString().split("T")[0];

  const s = StyleSheet.create({
    page: { padding: 40, fontFamily: "Helvetica", fontSize: 10, color: "#1a1a1a" },
    cover: { flex: 1, justifyContent: "center" as any, alignItems: "center" as any },
    coverTitle: { fontSize: 28, fontWeight: "bold", marginBottom: 8 },
    coverSub: { fontSize: 14, color: "#666", marginBottom: 20 },
    coverDate: { fontSize: 11, color: "#888" },
    coverTicker: { fontSize: 18, color: "#00aa66", fontWeight: "bold", marginBottom: 12 },
    h1: { fontSize: 16, fontWeight: "bold", marginBottom: 12, borderBottomWidth: 1, borderBottomColor: "#ddd", paddingBottom: 6 },
    h2: { fontSize: 13, fontWeight: "bold", marginBottom: 8, color: "#333" },
    entry: { marginBottom: 10, padding: 8, backgroundColor: "#f8f8f8", borderRadius: 4 },
    entryQ: { fontSize: 10, fontWeight: "bold", marginBottom: 4 },
    row: { flexDirection: "row" as any, justifyContent: "space-between" as any, marginBottom: 2 },
    lbl: { fontSize: 9, color: "#888" },
    val: { fontSize: 9, fontWeight: "bold" },
    green: { color: "#00aa66" },
    amber: { color: "#d4940a" },
    red: { color: "#cc3333" },
    para: { fontSize: 10, lineHeight: 1.5, color: "#444", marginBottom: 8 },
    disc: { fontSize: 9, color: "#888", lineHeight: 1.4, marginTop: 20 },
    foot: { position: "absolute" as any, bottom: 30, left: 40, right: 40, fontSize: 8, color: "#aaa", textAlign: "center" as any },
  });

  const tc = (t: string) => t === "HIGH" ? s.green : t === "MEDIUM" ? s.amber : s.red;
  const footer = React.createElement(Text, { style: s.foot }, "Generated by FinVerify Terminal \u2014 finverify-llm.vercel.app");

  const doc = React.createElement(Document, null,
    // Page 1: Cover
    React.createElement(Page, { size: "A4", style: s.page },
      React.createElement(View, { style: s.cover },
        React.createElement(Text, { style: s.coverTitle }, "FinVerify DVL"),
        React.createElement(Text, { style: s.coverSub }, "Audit Report"),
        ticker ? React.createElement(Text, { style: s.coverTicker }, ticker) : null,
        React.createElement(Text, { style: s.coverDate }, dateStr),
        React.createElement(Text, { style: { ...s.para, marginTop: 30 } },
          "Deterministic Verification Layer \u2014 Numerical Accuracy Audit"
        ),
      ),
      footer,
    ),
    // Page 2: Query Log
    React.createElement(Page, { size: "A4", style: s.page },
      React.createElement(Text, { style: s.h1 }, "DVL Verification Log"),
      React.createElement(Text, { style: { ...s.para, marginBottom: 12 } },
        `${entries.length} queries verified. Each entry shows raw LLM output, DVL-corrected value, applied rules, and trust.`
      ),
      ...entries.slice(0, 12).map((e, i) =>
        React.createElement(View, { key: i, style: s.entry },
          React.createElement(Text, { style: s.entryQ }, `${i + 1}. ${e.question}`),
          React.createElement(View, { style: s.row },
            React.createElement(Text, { style: s.lbl }, "Raw:"),
            React.createElement(Text, { style: s.val }, e.raw_number?.toFixed(4) ?? "N/A"),
          ),
          React.createElement(View, { style: s.row },
            React.createElement(Text, { style: s.lbl }, "Verified:"),
            React.createElement(Text, { style: { ...s.val, ...tc(e.trust_score) } }, e.verified_number?.toFixed(4) ?? "N/A"),
          ),
          e.correction_log.length > 0
            ? React.createElement(View, { style: s.row },
                React.createElement(Text, { style: s.lbl }, "Rule:"),
                React.createElement(Text, { style: { ...s.val, ...s.amber } }, e.correction_log.map(c => c.rule).join(" \u2192 ")),
              )
            : null,
          React.createElement(View, { style: s.row },
            React.createElement(Text, { style: s.lbl }, "Trust:"),
            React.createElement(Text, { style: { ...s.val, ...tc(e.trust_score) } }, e.trust_score),
          ),
        )
      ),
      footer,
    ),
    // Page 3: Methodology
    React.createElement(Page, { size: "A4", style: s.page },
      React.createElement(Text, { style: s.h1 }, "DVL Methodology"),
      React.createElement(Text, { style: s.h2 }, "Deterministic Verification Layer"),
      React.createElement(Text, { style: s.para },
        "The DVL is a post-inference correction system for LLM numerical outputs. Three-stage pipeline: scale correction (percentage-decimal confusion), sign correction (directional errors), magnitude correction (unit denomination). Validated on FinQA (n=873): 42x accuracy improvement on correctable errors."
      ),
      React.createElement(Text, { style: s.h2 }, "Trust Scoring"),
      React.createElement(Text, { style: s.para },
        "HIGH (green): No correction needed. MEDIUM (amber): Minor correction applied. LOW (red): Significant correction or flagged unreliable. Computed from correction magnitude relative to original value."
      ),
      React.createElement(Text, { style: s.h2 }, "Limitations"),
      React.createElement(Text, { style: s.para },
        "DVL corrects formatting-level errors only. Cannot fix reasoning errors (73.1% of remaining failures). When trust is MEDIUM/LOW, independently verify against primary sources."
      ),
      footer,
    ),
    // Page 4: Disclaimer
    React.createElement(Page, { size: "A4", style: s.page },
      React.createElement(Text, { style: s.h1 }, "Disclaimer"),
      React.createElement(Text, { style: s.disc }, "FOR INFORMATIONAL PURPOSES ONLY. NOT INVESTMENT ADVICE."),
      React.createElement(Text, { style: s.para },
        "This report is generated by the FinVerify DVL and is provided for informational and compliance documentation purposes only. Users should independently verify all financial figures against primary sources before making investment decisions."
      ),
      React.createElement(Text, { style: s.para },
        "FinVerify Terminal accepts no liability for any loss or damage arising from the use of this report. Past accuracy metrics reflect performance on a specific test set and may not generalize."
      ),
      React.createElement(Text, { style: { ...s.disc, marginTop: 40 } },
        `\u00a9 ${new Date().getFullYear()} FinVerify Terminal. All rights reserved.`
      ),
      footer,
    ),
  );

  return await pdf(doc).toBlob();
}

export default function DVLReport({ entries, ticker }: DVLReportProps) {
  const [generating, setGenerating] = useState(false);

  if (entries.length === 0) return null;

  const handleExport = async () => {
    setGenerating(true);
    try {
      const blob = await generatePDF(entries, ticker);
      const dateStr = new Date().toISOString().split("T")[0];
      const filename = `finverify_report_${ticker || "session"}_${dateStr}.pdf`;
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = filename;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } catch (e) {
      console.error("PDF generation failed:", e);
    } finally {
      setGenerating(false);
    }
  };

  return (
    <button
      onClick={handleExport}
      disabled={generating}
      className="flex items-center gap-1.5 px-2.5 py-1 text-[9px] font-mono font-bold uppercase tracking-wider text-t-cyan border border-t-cyan/30 rounded hover:bg-t-cyan/5 transition-colors disabled:opacity-50 disabled:cursor-wait"
    >
      {generating ? "GENERATING PDF..." : "↓ EXPORT REPORT"}
    </button>
  );
}
